version: '3'
services:
  postgres:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        BUILD_ENV: develop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cliq
      POSTGRES_USER: cliq
      POSTGRES_PASSWORD: cliq
    volumes:
      - ./data:/var/lib/postgresql/data