version: '3'
services:
    app:
        image: cliq-cqrs-service:${TAG}
        ports:
            - "8001:8001"
        env_file:
            - .env.local
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_ENV: develop
